### PR TITLE
Added compatibility with rails 4.1

### PR DESCRIPTION
**Pull request by TheNaoX**
looks like the options hash is not present on the newer versions of rails.

### CODE REVIEW

**Comment by dtropp** [comment]
I know this has been sitting here for a while, but any chance of merging this in and releasing a new gem version?

**Comment by nanocity** [comment]
Sorry, I'm about 2 years late.

**Comment by TheNaoX** [comment]
Cool!

**Comment by nanocity** [comment]
I will try to upgrade this gem, but it seems that is not easy to check "on" option with new callbacks API.

I haven't had time to investigate this in deep, but I think [this gem](https://github.com/beatrichartz/shoulda-callback-matchers) already have MongoID support.

Could you please confirm that? If they do not support MongoID, I can try to come up with something.

Thanks.

**Pull request merged**
